version: '1.0'
stages:
- clone
- misc
- test
- build
- release

# Requires SCALA_VERSION (x.y.z) to be specified
steps:
  get_github_token:
    title: Get default GitHub token
    stage: clone
    image: codefresh/cli
    commands:
    - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -r .spec.data.auth.password)

  main_clone:
    title: Clone main repository
    type: git-clone
    stage: clone
    git: github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}

  extract_xy_scala_version:
    title: Extract Scala x.y version
    stage: misc
    image: alpine:3.10
    commands:
    - cf_export SCALA_XY_VERSION="$(echo ${SCALA_VERSION} | cut -d '.' -f1,2)"

  test:
    title: Run unit tests
    stage: test
    image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    working_directory: ${{main_clone}}
    commands:
    - sbt -ivy /codefresh/volume/.ivy2 test

  build_jar:
    title: Build 
    stage: build
    image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    working_directory: ${{main_clone}}
    commands:
    - rm -f target/scala-${SCALA_XY_VERSION}/*.jar
    - sbt -ivy /codefresh/volume/.ivy2 assembly

  upload_jar:
    title: Upload release JAR
    stage: release
    image: guangie88/releaser:alpine_upx-3_ghr-0.12
    working_directory: ${{main_clone}}
    commands:
    - |-
      if [ -z "${CF_RELEASE_TAG}" ]; then
        TAG_NAME=experimental
      else
        TAG_NAME=${CF_RELEASE_TAG}
      fi
    - |-
      ghr -t ${{GITHUB_TOKEN}} -u ${{CF_REPO_OWNER}} -r ${{CF_REPO_NAME}} \
          -c ${{CF_REVISION}} -replace ${TAG_NAME} target/scala-${SCALA_XY_VERSION}/zeppelin-jar-loader-*.jar
